### ISSUE TITLE
Refresh Metadata takes a very long time

### ISSUE THREAD

**Issue by Anniedee** [ZenPhoto20/netPhotoGraphics#1006]
Hi, I am wondering if it is possible to further refine a feature in ZenPhoto20.  I use metadata extensively: I store all my image descriptions in the ITPC metadata. So whenever I upload a new folder of images, I run the utility to refresh the metadata. There are 3500 images on my site now (not a lot, actually) but it takes many hours to finish refreshing the metadata. And then I get errors from the server reporting excessive resource usage. 

So... what I'm asking: would it be possible to select a specific folder to refresh? I figure that would be more efficient than refreshing all of them. 

I love ZenPhoto20 for many reasons. 

Annie

**Comment by sbillard** [comment]
It already is possible. There is a refresh metadata acton by albums on the album list (the &#8635; icon) and on a button on the album page itself in the utilities section. You can even refresh for a single image on the image page, but you have to click the "edit all image data" link to get to the single image page.
