### ISSUE TITLE
Creation of a website dedicated to Zenphoto 20

### ISSUE THREAD

**Issue by ghost** [ZenPhoto20/netPhotoGraphics#809]
Hello, I contact you to make an important suggestion with ZenPhoto20. I want to create a site specifically dedicated to Zenphoto20.

The site will be multilingual and will be translated into several languages. English will be the default language. The goal of the site will be to increase the notoriety of Zenphoto20 and to make a difference with zenphoto.org.
The domain name I am going to buy will not be zenphoto20.com but another name more telling to Internet users, and that is good on reference to photography.
The aim of the site will be to promote zenphoto20 on the internet, to increase the engagement of Internet users thanks to the community help.

In addition, I would need your help to develop zenphoto20 website and make it a world reference for photography.
(sorry for my bad English)

cordially

**Comment by sbillard** [comment]
Sounds interesting. 

Of course, ZenPhoto20 will already be multi-lingual for the standard phrases. The site specific text you create will need translations into the various languages. The "source" language would be English. I will be glad to help you with creating proper English text.

What other specific help would you need in creating the site? As you probably know there are multiple themes you can choose from. If one is appropriate there is really little else that needs to be done other than providing content.

One other thing you might consider contributing--perhaps even more important than this proposed site--would be to bring the French language translations up-to-date with the current implementation. Our French translator has not been active for quite some time.

We recommend using PoEdit as your translation tool. You can then update translations and submit the results as a pull request.

**Comment by You85** [comment]
Hello @sbillard I contact you because you have more experience than me in programming.
What do you think is the best forum script currently? I thought of phpbb which is very complete.
Will you have a theme html / css to offer me. I found this one: https://www.free-css.com/free-css-templates/page227/exigo
Will you have domain name ideas to offer me, more speaking, which refers to cms, photography and multimedia?

**Comment by sbillard** [comment]
You can see the themes that ZenPhoto20 has to offer by browsing http://zenphoto20.us/demo/

There is a menu icon (☰) in the upper left corner that allows you to change the theme that is being displayed. These are the themes that you can choose from. ZenPhoto20 is a self-contained Photo/CMS software that is implemented primarily in PHP. It hardly matters what someone thinks is the "best" forum script. What matters is if there is a software that fits your needs.

The site you provided in your link above is one way to go. But it is not related to ZenPhoto20, so is not relevant to this conversation. Certainly if there is a design there you could replicate it with the ZenPhoto20 architecture. That would be a custom theme. Custom themes are supported by the ZenPhoto20 architecture. Two thirds of the themes you can select from on the demo site began their lives as a custom theme a user designed.

I am not personally in the business of making custom themes. But if you are competent in html/css it should not be difficult for you to take one of the existing themes and modify it. you can also review the themes at https://www.zenphoto.org/theme/ for ideas. There is a compatibility mode in ZenPhoto20 that would allow you to use them and there is a migration utility that will help you make them run natively.  

The names of websites specializing in cms, photography, and multimedia are pretty eclectic. Perhaps your target market is too broad? The trick to picking a website name is to guess what someone in your target audience will search on. Of course most of those guesses will likely already be taken.

**Comment by sbillard** [comment]
I like zenphotographics.com but that may appeal more to English speaking people.

**Comment by By-oussef** [comment]
Hello, @sbillard thank you for giving me your opinion. I bought the domain name and I ended up configuring phpbb after a hard day's work. Can you create an account so that I give you the rights of moderators.

Here is the forum of the website : https://zenphotographics.com/community/index.php

Cordially

**Comment by sbillard** [comment]
Done: user sbillard

**Comment by By-oussef** [comment]
Hello Thank you I am added as a moderator.
Can you change the name of Zenphoto20 script to Zenphotographics. Thank you.

Then I will improve several languages: Italian, Spanish and French.

Cordially

**Comment by By-oussef** [comment]
![zenphotographics logo](https://user-images.githubusercontent.com/41373170/42951862-7b7e15ae-8b77-11e8-9407-6cfb2c2ee7ca.png)

**Comment by sbillard** [comment]
Changing the name is not so simple. There are many people who will depend on the current name. Besides which the Github repository is ZenPhoto20. Possibly you could post on the google forum to suggest this change and announce your forum.

In the mean time I will investigate how it might be possible to migrate the repository.

**Comment by By-oussef** [comment]
I share your analysis. But in the long run people will be educated to this new name and it is very beneficial because it rejuvenates the image of the sript.

I posted a post on the Zenphoto20 google forum announcing the name change to Zenphographics.

**Comment by sbillard** [comment]
![zen-logo](https://user-images.githubusercontent.com/2474007/42972708-33f06b72-8b65-11e8-8a88-3ce8733ddf4a.png)

**Comment by sbillard** [comment]
This logo will not work everywhere, though. Probably have an alternate without the mountain for things like the "powered by" logo. Also need to replace 
![zp_gold](https://user-images.githubusercontent.com/2474007/42972767-77e660fc-8b65-11e8-9a26-d01738969116.png) with something, possibley justs the camera iris.

**Comment by By-oussef** [comment]
Hi, I will not be available until September because I have a problem in the family. I will come back in September and see what I can do.
Cordially

**Comment by sbillard** [comment]
No problem, it will take some time to make the changes needed to ZenPhoto20. But maybe you can give me admin access to the site. We will need to have both the BBS system and ZenPhotoGraphics sites operating together.  So I could start with that.

**Comment by sbillard** [comment]
Some work has been done on the name change https://github.com/sbillard/ZenPhoto20-DEV/tree/zenphotographics 

Discussions on these changes should be made on that repository until a formal change has been committed.

**Comment by sbillard** [comment]
The name will be netPhotoGraphics. The repository is changed, there is a new website [netPhotoGraphics.org](http://netPhotoGraphics.org) complete with BBS system  based on phpbb.

**Comment by sbillard** [comment]
The site has been created along with a BBS forum. 

When you get back form your family obligations let me know. Sign onto the new forum and I will make you a monitor. Let me know what else you would like.

**Comment by By-oussef** [comment]
Hi Billiards, I saw that you have created a dedicated website. Then I have administrator access to the site.

**Comment by sbillard** [comment]
Welcome back. yes, I decided on a different name, more of a break form 
the zenphoto stream. Also, things needed to move forward and you were 
unfortunately not available because of your family commitments.

Please log onto the site and I will give you the necessary permissions. 
Let me know the user/email you use for the site.


-Stephen

**Comment by By-oussef** [comment]
Done

**Comment by sbillard** [comment]
You should be setup now on the forum


-Stephen

**Comment by By-oussef** [comment]
Then I also have administrator access to the website netphotographics.org hosted on ipage.com
We can divide the roles roof you take care of the code and me of the site (I will manage the policy of refénrecement of the site in the search engines, I will create links towards this one in order to improve its classification, to make technical audit, translate the site to other languages, add content ...)

**Comment by sbillard** [comment]
I am a little confused. There can be only one domain: 
netphotographics.org the one I created is not hosted on ipage.com. Both 
the main site: netphotographics.org and the forum: 
netphotographics.org/forum are hosted on powweb.com.

What site is hosted on ipage.com? Your original zenphotographics.com 
one? That one seems no longer functioning.

As to the site translations: The primary text on the site is from the 
software itself, so contributing to those translation files will 
propagate to the site.

There is also a privacy policy page that could be translated as well as 
the welcome news article. The release notes articles are generated from 
the log I keep locally. I am not sure of the value of translating them, 
specially if that would require delays to the actual releases.

The users guide is currently a Word document. I suppose that could be 
converted into a series of pages with translations.


-Stephen

**Comment by By-oussef** [comment]
https://www.whoishostingthis.com/#search=netphotographics.org

**Comment by sbillard** [comment]
Interesting. I guess iPage and POWWeb are the same company. If you look 
at the name servers they are powweb.com.


-Stephen

**Comment by By-oussef** [comment]
Hi @bbillard gives you access to an administrator at Powweb to audit the site?

My adresse email is : youssef.elmourabit7@gmail.com

Thank You
