### ISSUE TITLE
ZoomImage plugin typo

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#814]
![dalsi](https://user-images.githubusercontent.com/7648991/43452623-2db2c71c-94b8-11e8-8c50-396d87489e53.jpg)

**Comment by sbillard** [comment]
Thanks.

**Comment by nerdykit** [comment]
Since you're at it, also same file line 18 thpe -->type

**Comment by sbillard** [comment]
Thanks.
