### ISSUE TITLE
googleTFA plugin - genereating "secret code"

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#815]
There are two way to add TFA to mobile phone - by QR code and by "secret code" (numbers and digits).

Is possible to add second way to gallery? It is usefull when user lost mobile phone and has this "secret code" save in (for example) password manager to restore generating codes in new device.

**Comment by sbillard** [comment]
If you hover over the qr image it will show you the secret code.

**Comment by sbillard** [comment]
I've added code so that it is easier to copy the secret code to the clipboard.

**Comment by Mates-K1** [comment]
Many thanks. 👍
