### ISSUE TITLE
Exceptions after upgrade to netPhotoGraphics version 1.8.0.02 

### ISSUE THREAD

**Issue by ncnetsec** [ZenPhoto20/netPhotoGraphics#820]
All links to albums have replacement broken image icon and these errors show.

{1034:Sat, 25 Aug 2018 20:03:25 GMT} netPhotoGraphics v1.8.0.02

EXCEPTION (0): "Call to a member function convert() on null" in /mnt/www/zp20/zp-core/functions-basic.php on line 201

URI:/zp-core/i.php?a=Year 2007/2007-07-30 Valle Crucis&i=LND_7330.JPG&w=248&h=125&cw=248&ch=125&q=75&c=1&t=1&wmk=!&check=9b720d306a1f909f7f2159fd4c57e66672f4539f&cached=280765750

IP `98.26.67.124`

zpExceptionHandler called from unknown
<img width="1128" alt="npg-info" src="https://user-images.githubusercontent.com/17273292/44622351-c93a7100-a884-11e8-927b-b2a19bf7c304.png">

**Comment by sbillard** [comment]
[setup-DEV-master-1.8.0.02.DEV_03.zip](https://github.com/ZenPhoto20/netPhotoGraphics/files/2321143/setup-DEV-master-1.8.0.02.DEV_03.zip)
See if this fixes the problem

**Comment by ncnetsec** [comment]
I unzipped the extract to the folder and all was well. Images were shown, even without running setup.  Ran setup and started using the skeleton theme.  Everything is working as far as I can tell.  Thanks for the quick turnaround.  Not sure why the filesystem is set the way it is.  The system started out as Ubuntu 12 and has been updated to 14, 16 and will probably get 18 in the next week or two.
