### ISSUE TITLE
Multilingual welcome message field in "Gallery options" for the login.php

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/netPhotoGraphics#823]
As discussed on the forum. Feature request. It would be really nice to have a field in the admin- "Gallery options" for a (Multilingual) welcome message in the login page. This for a private site. Preferably the welcome message would be above the password form (padbox) and underneath the header.

**Comment by sbillard** [comment]
[setup-DEV-master-1.8.0.04.DEV_02.zip](https://github.com/ZenPhoto20/netPhotoGraphics/files/2325279/setup-DEV-master-1.8.0.04.DEV_02.zip)

See if this is what you want.

**Comment by Elinth** [comment]
Hi Stephen,

I really like it. My initial thought was to place it above the login box. But that would be theme specific won't it?

**Comment by Elinth** [comment]
The fact is I have it working on my site above the login box. The fact is that the way I currently do it is via <?php printPageContent>. But that means this page also shows up as an item in the zenpage pages in the main menu. Which is not ideal.

**Comment by sbillard** [comment]
This implementation adds the message as part of the login box. How the logon box is shown is very theme dependent. Plus, if you simply go to the admin page link you get a logon box without any theme page.
