### ISSUE TITLE
Prevent file from being overwritten by upgrade

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#825]
I've had to create a new set of light coloured slideshow control icons because my background is very dark.  Every time I upgrade, nPG my custom file slideshow-controls.png is overwritten.  Is there any way to "protect" this file?  I do keep a copy of my version handy but with the frequency of updates, it's a pain to have to copy it into place over the version installed by the master and half the time I forget to do it, rendering the slideshow almost impossible to start/stop/pause.

**Comment by sbillard** [comment]
slideshow uses getPlugin('slideshow/slideshow.css', getCurrentTheme(), true); to get the CSS. This looks first in the user plugin folder, then the theme folder, and finally in the slideshow folder. So you would need to put a copy of the CSS and your images in "plugins/slideshow". Unfortunately slideshow2 does not do this. That will be fixed.

**Comment by sbillard** [comment]
Update: I was wrong, slideshow2 does get the css correctly.

**Comment by nerdykit** [comment]
Thanks, I'll make sure that the css in the user plugin folder or theme folder (it's a custom theme-just a few modifications of basic theme) is correct for my set of controls and see if it survives an upgrade.

**Comment by sbillard** [comment]
So long as it is in a custom theme or in the user plugin folders it will survive. only the "core" and distributed themes and user plugins are overwritten. This technique was designed with just your situation in mind.

**Comment by nerdykit** [comment]
Thanks, by user plugin folder, I'm assuming that you mean the plugins folder at the top level of the setup, with the "system installed" plugins being in zp-extensions inside zp-core.  Second question...does locale work the same way?  I've got a couple of items setup in locale that are custom (canada english and french) and while they are not overwritten, I do get an 'extra files' warning on every install and if there's a lot of extra files because of a change that you've made, the files I'd like to keep are mixed in with the ones that would be deleted and so I can't just let the installer delete them all or I'd lose my own locale files at the same time.  If I made a top-level locale folder and put my custom locales in there would they then not be flagged as 'extra' files?

**Comment by sbillard** [comment]
Yes, the top level "plugins" folder is where they go. Locale does not work that way at present. Maybe it could....

Or you could contribute your Canadian English and French translations!

**Comment by sbillard** [comment]
Sorry, the gettext handling in PHP wants all the locale files all in the same folder so the getPlugin() trick cannot work. What would work is a plugin that copied the files from some safe resting place. you would not even have to enable it. Setup loads all plugins when it runs. The define OFFSET_PATH has the value 2 during setup, so the plugin could simply be an if statement as below:

`if (OFFSSET_PATH==2) {
@mkdir_recursive(SERVERPATH.'/'.ZENFOLDER.'/locale/en_CN/LC_MESSAGES', FOLDER_MOD)
  @copy(<FLAG IMAGE>, SERVERPATH.'/'.ZENFOLDER.'/locale/en_CN/');
  @copy(<MO FILE>, SERVERPATH.'/'.ZENFOLDER.'/locale/en_CN/LC_MESSAGES');
  @copy(<PO FILE>, SERVERPATH.'/'.ZENFOLDER.'/locale/en_CN/LC_MESSAGES');
}`

The offer still stands to distribute your translations.

**Comment by sbillard** [comment]
I guess there will be some issue on flags--how does one tell the difference between the flag for en_CA and for fr_CA? I suppose that the title pop-up would do, but I imagine using the same flag might be confusing.

If it is just the flags that are changed then there is probably no advantage to distributing the translations.  But it wouldn't hurt if you reviewed the french translations to see if they make sense. !7% of the translations are generated from Microsoft Translator. (Those are marked "fuzzy")

Anyway, if the translations are just the distributed ones in disguise the plugin can simply copy trom the standard ones so all you have to park are the flags.

**Comment by nerdykit** [comment]
Just rummaged around and I don't think that there's a english language LC_Messages folder anywhere so no default set of english strings to "translate".

**Comment by sbillard** [comment]
No, English US is the source language. A new translation needs to be made for Canadien.

**Comment by nerdykit** [comment]
I can report that when I set up the custom slideshow controls image in the user plug-ins directory that my custom image survives installation of an upgrade as you've said it would.  I'll look into the French translation locale files and see what I (or my friends with better French language skills than mine) can do.  It's not worth bothering to try to come up with a Canadian English "translation", it's too trivial for the amount of work it would take.  Thanks.  Will close this issue.
