### ISSUE TITLE
Possible error in locale files

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#829]
While editing the french language file I noticed that the English "source" for string 31 probably contains an error.  There's a couple of `<code>  </code>` tags in it but on string 31 the first pair is not properly closed (missing /).  This minor error might exist only for the file I was using or it might exist across all the source text in all of the zenphoto.po files in locale directory.  Since the source strings probably match with strings within the program files, the error (if it really is an error) might exist in the program file too.

**Comment by sbillard** [comment]
So, I need a bit of help finding this string. (string 31 is not something I can figure out.) Probably just the test of the string will do. But the .po file also gives a file/line number.

**Comment by nerdykit** [comment]
Sorry I thought that was an item number from the po file but I see that it's just a poedit ID.

While looking for the line I wanted to flag, I also found... (line 138)
```
#: plugins/MyBB_auth.php:121
#, fuzzy
#| msgid "Database password"
msgid "The MyBB database passwrod."
msgstr "Le passwrod de base de données de MyBB."
 
```
and the one I originally found... (line 198)

```
#: plugins/SpellflightRedirect.php:12
msgid ""
"Redirect link <code>site/ContactLost<code> to <code>site/pages/ContactLost</"
"code>."
msgstr ""
"Rediriger lien <code>site/ContactLost </code>to <code>site/pages/"
"ContactLost</code>."

```

**Comment by sbillard** [comment]
Thanks. Don't worry about that, though. That file is actually not part of the distribution. Guess I will have to figure out how to avoid these local files:) Anyway, somehow it will get fixed.

**Comment by sbillard** [comment]
I looked in my .po files and the string does not show there. Are you sure you are using a current version of the French translation? Are you using PoEdit? It has a menu catalog/purge deleted translations that will clean up the orphans.

**Comment by nerdykit** [comment]
Based on the date on the files I created in locale directory to deal with en_CA and fr_CA I did that in late June of this year.  I'll take a look in to some of them and see if it really is a problem (even if it is trivial).  I just assumed that the standard locale folders were all re-written whenever an upgrade was done.

**Comment by nerdykit** [comment]
Don't waste your valuable time working on preserving a user's custom locale files.  I've updated my own version and now will close this issue.

**Comment by sbillard** [comment]
I've just updated the .po files, so you should get a copy from gitHub so for sure all deleted translations have been purged. Also changed the project name to netPhotoGraphics for what that is worth.
