### ISSUE TITLE
Search not find some MP4 files

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#830]
Latest 07 build.

I will start a little bit wide:
- sometimes my ClassVideo plugin is deactivated (I dont know why, about 1x per month),
- I lost all my MP4 video titles (I do not know the exact date), not description or tags
- I use only MP4 for videos in my gallery
- I use only ClassVideo plugin, not JPlayer or VideoJS,
- after refreshing DB and metadata, there are 3 hanging FLV files
```
{61839:Mon, 03 Sep 2018 10:11:29 GMT}
Bad filename suffix in newImage(31.flv)
URI:/zp-core/admin-refresh-metadata.php?tab=prune&refresh=start&XSRFToken=..............
newImage called from Gallery->garbageCollect (class-gallery.php [743])
from admin-refresh-metadata.php [39]
```

And now main problem - searching not find all MP4 files. Searching returns only 35 from about 230 files. If I "manually" go to another MP4 file, I can see it, play it including poster.

Finding JPG or PDF works.

![6dfb6b75-e579-4b19-858d-22f44cfb0592](https://user-images.githubusercontent.com/7648991/44982330-da1a6f00-af75-11e8-82f4-838a739c18d6.jpg)

**Comment by Mates-K1** [comment]
I did a small inspection in my DB and I am a little bit confused.

In DB, in images table, there are many obsolete values for FLV files that I used.

There is file 021.mp4 with ID 22942.
![710b9b55-c7a2-4c39-8e34-1f1c9323ef00](https://user-images.githubusercontent.com/7648991/44985863-2c618d00-af82-11e8-8389-46c8051b4a55.jpg)

But my DB ends with file with ID 20426.
![c9457cda-492d-44a7-b231-635d0fd45285](https://user-images.githubusercontent.com/7648991/44985942-777ba000-af82-11e8-9a82-d19b353936bb.jpg)

... and there isnt the same file in whole DB that matched, BUT there is a file which matched by description - 021.flv with ID 19171.

Possible reason??? I change FLV files to MP4. I upload (FTP) 01.mp4 to folder where is 01.flv and 01.jpg (poster) files. At this moment I have both videos in gallery. In backend I copy (CTRL+C,..) title, desc, add tags to new file (01.mp4), then delete (FTP) file 01.flv.

**Comment by Mates-K1** [comment]
ClassVideo plugin - ok, I will look at that way

MP4 videos - there is a problem with metadata... with video poster EXIF.

```
{30646:Tue, 04 Sep 2018 09:05:11 GMT}
WARNING: "exif_read_data(015.jpg): Illegal IFD size" in /data/web/virtuals/172972/virtual/www/zp-core/functions-image.php on line 551
URI:/zp-core/i.php?a=1_oddil_skautek/tabory/2008&i=015.jpg&s=80&cw=80&ch=80&t=1&check=4236cfd2485114859c228a60ed27cd455d15b078&cached=615554622
exif_read_data called from getImageRotation (functions-image.php [551])
from cacheImage (functions-image.php [179])
from i.php [163]

{30646:Tue, 04 Sep 2018 09:05:11 GMT}
WARNING: "Cannot modify header information - headers already sent by (output started at /data/web/virtuals/172972/virtual/www/zp-core/functions-basic.php:145)" in /data/web/virtuals/172972/virtual/www/zp-core/i.php on line 198
URI:/zp-core/i.php?a=1_oddil_skautek/tabory/2008&i=015.jpg&s=80&cw=80&ch=80&t=1&check=4236cfd2485114859c228a60ed27cd455d15b078&cached=615554622
header called from i.php [198]

{30646:Tue, 04 Sep 2018 09:05:11 GMT}
WARNING: "Cannot modify header information - headers already sent by (output started at /data/web/virtuals/172972/virtual/www/zp-core/functions-basic.php:145)" in /data/web/virtuals/172972/virtual/www/zp-core/i.php on line 199
URI:/zp-core/i.php?a=1_oddil_skautek/tabory/2008&i=015.jpg&s=80&cw=80&ch=80&t=1&check=4236cfd2485114859c228a60ed27cd455d15b078&cached=615554622
header called from i.php [199]

{30646:Tue, 04 Sep 2018 09:05:11 GMT}
WARNING: "Cannot modify header information - headers already sent by (output started at /data/web/virtuals/172972/virtual/www/zp-core/functions-basic.php:145)" in /data/web/virtuals/172972/virtual/www/zp-core/i.php on line 201
URI:/zp-core/i.php?a=1_oddil_skautek/tabory/2008&i=015.jpg&s=80&cw=80&ch=80&t=1&check=4236cfd2485114859c228a60ed27cd455d15b078&cached=615554622
header called from i.php [201]
```

There is one of img with "corrupted" EXIF.  By http://exif.regex.info/exif.cgi it says "Warning: Bad IFD1 directory".
![015](https://user-images.githubusercontent.com/7648991/45025657-58d9df80-b03c-11e8-95ed-f58429e29adb.jpg)

It seems some of corrupted posters can by repaired by gallery by refreshing metadata (but publish date is set to present).

For bad poster is typical:
- no thumb in album,
- no result in search.

After a little bit googling I foud that there is propably bug in one of my photo editor (saving EXIF). Did something change in the gallery? Because it works with those posters many years.

**Comment by sbillard** [comment]
Nothing changed with netPhotoGraphics, however, the function that is throwing the error is a PHP function, so maybe something changed with PHP. It is possible to ignore the error (and not try to rotate the image, which is what is going on.) I will include that in the next update.

**Comment by Mates-K1** [comment]
Thanks for explaining this. :)

**Comment by sbillard** [comment]
Refreshing the metadata does not alter the publish date directly. It does update the "mtime" date (which is the date the filesystem says the image was last "changed.") If the refresh thinks it has not seen the image before, then it would set the publish date (presuming that you have chosen to auto-publish new images.)

My guess is that the bad poster is causing the image not to be entered in the database in the first place. That would explain your symptoms.

Anyway, 
[setup-DEV-master-1.8.0.09.DEV_02.zip](https://github.com/ZenPhoto20/netPhotoGraphics/files/2362907/setup-DEV-master-1.8.0.09.DEV_02.zip)
should not throw the error.

**Comment by sbillard** [comment]
Is this issue resolved? If not, what it the current situation.

**Comment by Mates-K1** [comment]
Sorry for the late reply.
So... after some db refreshing, it seems that the number of images is OK. Titles are still lost.
I dont care about time changing, it is not important for me in this case. :)

After searching I really found some lost FLV files that did not show up in gallery. So I switched them to MP4 and now it seems all works.

I think this case was combination of outdated DB, damaged posters and my atypical behavior (upload FLV, then poster and MP4).

For me, we can close this ticket. Thanks for help.
