### ISSUE TITLE
issue with MySQL max connections improvements

### ISSUE THREAD

**Issue by vincent3569** [ZenPhoto20/netPhotoGraphics#845]
the commit https://github.com/ZenPhoto20/netPhotoGraphics/commit/8b782cce95516d3055542e69060be16667c04b87 seems to not work well

```
 {6954:Fri, 12 Oct 2018 06:54:59 GMT} netPhotoGraphics v1.8.1.01	
ERREUR GÉNÉRÉE PAR L’UTILISATEUR : Erreur MySQLi : DELETE FROM `zp_plugin_storage` WHERE `type`="cacheManager" AND `subtype`='' AND `aux`='slideshow' a échoué. MySQLi a renvoyé l’erreur User avbo7291_zpuser already has more than 'max_user_connections' active connections dans /.../public_html/zenphoto__dev/zp-core/functions-basic.php à la ligne 87
URI:/zp-core/setup/setup_pluginOptions.php?plugin=slideshow&class=0&from=1.8.1.01&unique=1539327296
IP `xxx.xxx.xxx.xxx`
utilisateur:
trigger_error called from zp_error (functions-basic.php [87])
from dbErrorReport (functions-basic.php [37])
from db_query (functions-db-MySQLi.php [87])
from query (functions-basic.php [415])
from cacheManager::deleteCacheSizes (cacheManager.php [429])
from slideshow->__construct (slideshow.php [88])
from setup_pluginOptions.php [59] 
```

I have a lot of other similar errors in my debug log

**Comment by sbillard** [comment]
What are the values of Max connections and connections used from the installation analysis admin page?

**Comment by vincent3569** [comment]
hi Stephen

> What are the values of Max connections and connections used from the installation analysis admin page?
Database name: zenphoto_dev; Max connections: 500, Connections used: 96 

> Also, how many plugins and themes are in your installation?
12 active plugins, 35 active filters, and 14 themes of your package.

**Comment by sbillard** [comment]
Total plugins is what I wanted--the number that run during setup. But it probably does not matter. With about 400 available connections I doubt that the number of plugins matter.

I have to guess that these connections are shared by all your host's applications. There is no way that netPhotoGraphics can use 500 connections by itself. Besides which, with the commit it should be using somewhere around 30 connections at the most. So something else is going on.

Unfortunately, one has to connect to the database to get the answer of how many connections are available, so that is pretty useless if there are no connections available.

Could you sample the Max connections and connections  used over a bit of time? I wonder how much it varies.

**Comment by sbillard** [comment]
Please try 1.8.1.02 and see if this is improved

**Comment by vincent3569** [comment]
I still have red crosses on some plugins but I have none on themes et sur mod_rewrite.
and also, I don't have anything in my debug log.

![screenshot014](https://user-images.githubusercontent.com/1224809/47000959-bb3cfa00-d129-11e8-94d8-ad769b60e5f3.png)

**Comment by sbillard** [comment]
In the setup log there should be a line showing the setup concurrency. What is that value? I suspect that the red x'es are due to the browser timeout waiting for the image since there are no errors in the log. Did the setup log show any errors?

I will look and see if that wait can be extended.

**Comment by vincent3569** [comment]
as far I can see the is no line showing setup concurrency.

`netPhotoGraphics Setup v1.8.1.04: Tue, 16 Oct 2018 23:26:16 +0200
Warn: PHP version 7.0.32
PHP Version 5.2 or greater is required. Version 7.1 or greater is strongly recommended as earlier versions may not be actively supported. Use earlier versions at your own risk.
Completed system check
Database update is not required.
Set default options
Completed with errors`

**Comment by sbillard** [comment]
Probably is a debug only setting. But no matter, I have finally figured out how to generate these connection errors. No solution yet, but progress.

**Comment by sbillard** [comment]
Let's see how 1.8.1.05 does

**Comment by sbillard** [comment]
Testing is complete with version 1.8.1.08, Setup runs successfully so long as there are at least 3 MySQL connections available on my test system.
