### ISSUE TITLE
Result of clicking on a displayed image

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#858]
When I click on an image on an image page, I used to then get a display of the full size image, now I'm getting a small red X image.  I think that this is a setting that either I've changed or has had its default value changed but I can't find out which setting that is.  Can you guide me to the correct settings place so that I can restore the behavior?  What I want is for users to have access to the full image if they click on the image from the page displaying that image.

**Comment by sbillard** [comment]
The link for full images is produced by getFullImageURL(), so that would be one starting place. The image can be loaded directly from its source or it can be "protected". What is the link text for your links?

Have you tried other themes to see if the problem is universal?

**Comment by nerdykit** [comment]
I don't think I properly understood that the "click on a displayed image" behavior was a theme related response (I think I've only ever used the Basic Theme).  So now I can see different behaviors depending on which theme I use.  I'm going to close this issue, tinker with my version of the Basic theme and see if that's what I've got to fix.  If I need help I'll get back to you.  Thanks
