### ISSUE TITLE
Options -> General - small backend enhancement

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#861]
![001](https://user-images.githubusercontent.com/7648991/48761253-7ec06900-eca8-11e8-972c-ddff0df5bfc8.png)

1) first letters are usually small in gallery (for options)

2) missing space between text and input

**Comment by Mates-K1** [comment]
The same (yes or not first letter up) is for Policy URL and Notice text... and for Admin pagination (User, Plugins... per page).

**Comment by Mates-K1** [comment]
And could be this site as nice as Gallery page please?

Page General:
![002](https://user-images.githubusercontent.com/7648991/48762845-37d47280-ecac-11e8-9751-680349c4e61e.png)


Page Gallery:
![003](https://user-images.githubusercontent.com/7648991/48762866-41f67100-ecac-11e8-9d87-0bd2895987db.png)

**Comment by sbillard** [comment]
I did not fix the cookie duration. It is a simple number and does not need the full width

**Comment by Mates-K1** [comment]
Many thanks... 
but:
![001](https://user-images.githubusercontent.com/7648991/48930773-fd104b80-eef2-11e8-91e5-180f9526abb6.png)

![002](https://user-images.githubusercontent.com/7648991/48930774-000b3c00-eef3-11e8-9c4a-caae3a1a4096.png)
