### ISSUE TITLE
Search by tags not working

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#866]
clicked in error but can't delete this, please ignore and look at the comment for the actual issue

**Comment by nerdykit** [comment]
As far as I can see, a Search using a tag does not work.  Searches by Title or Description work but not by tags.  I've tried different themes, and verified that the tags are correctly attached to their images but still results come up empty on a tag based search.  The check box for tags is checked.

**Comment by sbillard** [comment]
I confirm something seems broken. I will look into it as soon as I can. But I have visitors this week, so it may be a bit delayed.

**Comment by nerdykit** [comment]
Not a problem.  Enjoy your time with the visitors.  There is no rush.

**Comment by nerdykit** [comment]
Thanks.  The fix works.
