### ISSUE TITLE
Possible issue in Search options re: language specific tags

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#868]
When in Options-->Search, all three radio buttons for "language specific tags" show as not selected and even if one radio button is selected, a return to the same page still shows no pre-existing selection.

After a change is applied, the state of that change does not show in the radio buttons.   Not sure if this is a bug or just the way it was intended to function.

**Comment by sbillard** [comment]
For me the only one that has a problem is setting the option OFF. "generic" and "specific" work. The OFF issue is a bug.

**Comment by nerdykit** [comment]
Thanks.  I was only wanting to use OFF so didn't test the others.  This is now fixed.  Thanks
