### ISSUE TITLE
version numbers may be incorrect

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#871]
Your email just received announces 1.9.0.2 but the actual installation and the banner at the main admin page announce (and all of the install) is of 1.9.0.3  It hardly matters but I thought I'd point out the discrepancy.

NK

**Comment by sbillard** [comment]
Well, when the e-mail was sent it was 1.9.0.2, but there has been an update (to include fixes to your issues among other things.)  the current bug fix build is 1.9.0.3 which went up this morning. 

Just out of curiosity, what e-mail are you referring to? I'm not aware of sending one specific to 1.9.0.2.

**Comment by nerdykit** [comment]
Sorry, the email I meant was the one generated automatically by Github when you "publish" a new version.  I did not mean an email from you personally.  Will close this, it's not relevant and it's not an issue.

**Comment by sbillard** [comment]
Sorry, that is an artifact of how I do releases. I do the development on my own clone of the code, then push it to the netPhotoGraphics repository. Then from that repository I change the release number. In this case there was a version 1.9.0.2 that was never put into a formal release build. Guess when I pushed the changes that version number was flagged and sent out. 

I suppose you will get a notice of 1.9.0.3 as well.
