### ISSUE TITLE
Use lazysizes to improve the loading of the web page

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/netPhotoGraphics#875]
Use lazysizes to improve the loading of the web page because currently chevereto loads several images even the one located below the waterline or it would be necessary to display the images on which is the screen of the computer and not that located in below the screen. lazysizes has several advantages it allows to improve the seo, the performances, the user experience because the images are displayed more quickly and it is very popular this script has more than 9000 stars on github. https://github.com/aFarkas/lazysizes

**Comment by sbillard** [comment]
netPHotoGraphics has a a plugin which does lazy loading of images.
