### ISSUE TITLE
Problem - can't switch themes

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#878]
I find that I can't switch themes from the Admin page for themes.  I get this error...

Error: the requested object was not found.
Album: zp-core/admin-tabs/admin-tabs/themes.php 

...when I try to select a different theme.

Looks to me as if the admin-tabs duplication is the issue.  Using Theme Basic (which I forced a switch to as the "default" by renaming my former theme with a couple of XX).  I was using a custom variant of Basic before this but thought that since I was getting this bug, I should probably be using Basic instead so made the "switch" as noted above.  The error persisted even using Basic.  Haven't tried other themes because it's not possible to switch to using them.

**Comment by sbillard** [comment]
You are correct. The quick fix is to change line 286 to read 

<a onclick="launchScript('', ['action=settheme', 'themealbum=<?php echo pathurlencode($alb); ?>', 'theme=<?php echo urlencode($theme); ?>', 'XSRFToken=<?php echo getXSRFToken('admin-tabs/themes') ?>']);">

That is the first parameter is an empty string.

**Comment by nerdykit** [comment]
Sorry, something ate part of your response.  Not clear what the edit to line 286 should be.  Assuming this edit is to themes.php

**Comment by nerdykit** [comment]
Figured out how you want me to edit line 286.  Removing content of first parameter and leaving empty single quotes does it.  Looks as if other lines close to it may carry the same problem but I'm not going to touch them.  I can now switch themes.

**Comment by sbillard** [comment]
Sorry forgot about not inserting `<` and `>` signs in a posting. But you did figure it out correctly. I'll look at the other lines.
