### ISSUE TITLE
New- a red X in my custom theme when I run setup on 1.9.0.04

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#879]
I use a very small number of edits in the CSS to Basic as my custom theme.  As of installation of 1.9.0.04 I'm now seeing a red X appearing on my custom theme and also on slideshow plugin.  What does the red X signify beyond "I don't like it" ?  Can I modify my adjustments to make the red X go away when I run setup?  How serious is this problem?

**Comment by sbillard** [comment]
e red XZ means there was an error during setup. Click on the Red X and you will get a page of the setup execution of the theme/plugin. That should show the error. It may also be in the debug log. Sometimes you get the Red X when the browser does not wait long enough for the script to run and serve the checkmark image. If you click on the red X and get a check mark, then this was the case.

**Comment by sbillard** [comment]
Is this issue resolved?

**Comment by nerdykit** [comment]
Yes.  Sorry, I thought it had been closed.
