### ISSUE TITLE
Bad link from Overview -> Search analysis (1.9.0.05)

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#882]
![obrazek](https://user-images.githubusercontent.com/7648991/51332276-b74bab80-1a7b-11e9-91cd-a6a3b27ee835.png)

Click "Change Tresholds values" and get:

![obrazek](https://user-images.githubusercontent.com/7648991/51332350-e06c3c00-1a7b-11e9-935a-2050cd81da0f.png)

**Comment by sbillard** [comment]
Thanks, fixed a few similar ones as well.
