### ISSUE TITLE
Feature request - Plugin that transfers data to netphotographics

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/netPhotoGraphics#884]
It would be interresting and in order to make netphotographics more popular to allow to transfer data from piwigo, chevereto or wordpress to netphotographics.
It would be necessary to export the titles, the images, the descirptions, comments, tags, urls, the number of view, the pages, ...
Please @sbillard do not close this post I really need this plugin.

Like this : https://www.zenphoto.org/news/nirvana-gallery3-to-zenphoto-migration/

**Comment by sbillard** [comment]
There are plugins that exists to port gallery3, piwigo , and wordpress to Zenphoto. Why not just use them? Zenphoto plugins are compatible or easily ported to netPhotoGraphics.

As for chevereto, you've already suggested need previously for a friend, haven't you. I believe I responded to that request. I am not willing to expend the effort to learn these softwares without aid or compensation. I am willing to partner with someone with the knowledge to create the migration tool. (Or migration instructions depending on what is learned.) If someone wants me to do the work alone, it will have to be commissioned. Without someone with the knowledge of those systems and the desire to port them to netPhotoGraphics it would be a waste of my time to pursue this request.

So, unless you can come up with a partnership this ticket will get closed. I give it a week for your response.
