### ISSUE TITLE
jPlayer does not play videos

### ISSUE THREAD

**Issue by sbillard** [ZenPhoto20/netPhotoGraphics#908]
Using jPlayer to play an mp4 gives an "Update required" message. Native HTML5 works as does the VideoJS plugin

**Comment by JimBrown** [comment]
'm aware of that. Next on my to do list after going through the album.php files. (Works fine in zenFluid. ;-) ).

...jim

**Comment by sbillard** [comment]
Found the problem. It was my fault!
