### ISSUE TITLE
Missing title in "Cache as"

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#915]
1.9.2.03
![a](https://user-images.githubusercontent.com/7648991/53935382-5ec18380-40a6-11e9-95f8-7f39ab661a45.png)

**Comment by sbillard** [comment]
Can you look at the supported image types in your installation information and tell me if "webp" is present?

**Comment by sbillard** [comment]
Also, are you using the GD library or ImageMagic?

**Comment by Mates-K1** [comment]
Hope it will help...

![obrazek](https://user-images.githubusercontent.com/7648991/53977748-045a0e80-410a-11e9-943e-f9487fb0e007.png)

**Comment by sbillard** [comment]
Ok, that is the information I needed. There is a bug in handling when the webp format is not supported. Fix is on the way.

**Comment by Mates-K1** [comment]
Many thanks. 👍
