### ISSUE TITLE
macrolist plugin description

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#926]
Please check macrolist plugin desctiption.... I think there are extra information...
![obrazek](https://user-images.githubusercontent.com/7648991/54189545-50aea100-44b2-11e9-940a-399dfc1706b5.png)

![obrazek](https://user-images.githubusercontent.com/7648991/54189601-6fad3300-44b2-11e9-9147-e56417b3ae53.png)

**Comment by sbillard** [comment]
This is very interesting. I see this wrong information, but it is not part of the actual plugin. Have to figure out where it is coming from!
