### ISSUE TITLE
New automated install report

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#927]
Just thought I'd provide a report on the new automated install process.  Will close this issue afterward.  Clicking the install button (upgrading 1.9.2.05 to 1.9.2.09) caused the download to happen successfully.  I DID get a cross-posting warning but even so, admin then reported the presence of an extract.php.bin file and clicking on the install button again provided a seamless standard upgrade.  So, congratulations!  Server is a local server (raspberry pi running raspbian).

Cheers

NK

**Comment by sbillard** [comment]
Thanks for the report. I have fixed the cross-posting issue, but of course it will last until after the install of the release with the fix.

I do have one test site where the `allow_url_fopen` option is disabled. If that is the case you get an error message and have to upload the setup zip file (or the extract.php.bin file) directly. Then all goes according to plan.
