### ISSUE TITLE
Error after update - after enabling some metadata

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#931]
1.9.2.09.DEV_03
Enabling some metadata, then:
![obrazek](https://user-images.githubusercontent.com/7648991/54950384-74a5c400-4f41-11e9-9e3e-9dc6735d485d.png)
then run update....

![obrazek](https://user-images.githubusercontent.com/7648991/54950233-1f69b280-4f41-11e9-986b-c7bc47771896.png)

**Comment by sbillard** [comment]
Seems that there is a caching issue. If you re-run setup things will work. Fix is on the way.
