### ISSUE TITLE
Undefined index when enable OpenStreetMap plugin

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#956]
![obrazek](https://user-images.githubusercontent.com/7648991/55934862-5377ef80-5c32-11e9-87ad-c3c0ae81662e.png)

**Comment by Mates-K1** [comment]
...and when switching theme
![obrazek](https://user-images.githubusercontent.com/7648991/55952953-23911200-5c5b-11e9-84f0-69b692fa7dfb.png)

**Comment by Mates-K1** [comment]
![obrazek](https://user-images.githubusercontent.com/7648991/55956596-9b176f00-5c64-11e9-98ed-fce9632bf438.png)

**Comment by sbillard** [comment]
There is now a development build that I think will fix these. But I need you to verify.
https://github.com/sbillard/netPhotoGraphics-DEV/releases/tag/netPhotoGraphics-1.9.0.0

What version were you running when these errors occurred?

**Comment by Mates-K1** [comment]
Version 1.9.3.03.

It seems work, you are amazing!!! 

I get only one exception: 

`EXCEPTION (0): "Call to undefined method openStreetMap::getTitleProviders()" in /data/web/virtuals/172972/virtual/www/zp-core/zp-extensions/openstreetmap.php on line 419 `

and map is not shown.

How code I would to place to image.php? I cant find any information about this. :/
`<?php printOpenStreetMap(); ?>`?

**Comment by sbillard** [comment]
There is an update to the dev repository for this

**Comment by Mates-K1** [comment]
from Firefox:
![obrazek](https://user-images.githubusercontent.com/7648991/56013665-386cb480-5cf2-11e9-8bbd-764a44283d61.png)

from MS Edge:
![obrazek](https://user-images.githubusercontent.com/7648991/56013706-5df9be00-5cf2-11e9-89e3-95ce114263eb.png)

**Comment by sbillard** [comment]
I will need to reproduce this locally. Can you provide me with your openstreetmap option settings so I can set up the same situation. Perhaps also the images you are viewing.

**Comment by sbillard** [comment]
Please also view the "page source" of this page with your browser. There should be some javascript similar to:
`

ript>
--
  | var geodata = new Array();
  | geodata[0] = {
  | lat : "33.682833333056",
  | long : "-118.03549999997",
  | title : "<br />",
  | desc : "",
  | thumb : "<a href='/dev/gps/20081230_145249-slb.JPG.htm'><img src='/dev/zp-core/i.php?a=gps&i=20081230_145249-slb.JPG&s=150&cw=0&ch=0&q=75&t=1&wmk=!&limit=15&check=d42ae7f7dcf1f9d88be3212738d376060cfd96e8&cached=760420236' alt='' /></a>",
  | current : "0"
  | };				var map = L.map('osm_map', {
  | center: [33.682833333056,-118.03549999997],
  | zoom: 4, //option
  | zoomControl: false, // disable so we can position it below
  | minZoom: 2,
  | maxZoom: 18							});

`
What does yours look like? Is this a single image page or an album page?

**Comment by Mates-K1** [comment]
```

			<script>
				var geodata = new Array();
			 geodata[0] = {
                  lat : "50,076035833333",
                  long : "16,474212",
                  title : "Hrab\u00e1n\u00ed list\u00ed na z\u00e1meck\u00e9m h\u0159bitov\u011b<br />",
                  desc : "",
                  thumb : "<a href='/index.php?album=1_oddil_skautek/brigady/brigada_1991_uklid_zameckeho_hrbitova&image=02.jpg'><img src='/zp-core/i.php?a=1_oddil_skautek/brigady/brigada_1991_uklid_zameckeho_hrbitova&i=02.jpg&s=150&cw=0&ch=0&q=75&t=1&wmk=!&limit=30&check=1f48e0a3592fe62cb480f6d20b454e347ebd1764&cached=1692765520' alt='' /></a>",
                  current : "0"
                };				var map = L.map('osm_map', {
					center: [50,076035833333,16,474212],
					zoom: 4, //option
					zoomControl: false, // disable so we can position it below
					minZoom: 2,
									maxZoom: 18							});
			L.tileLayer.provider('OpenTopoMap').addTo(map);					L.control.scale().addTo(map);
			
				L.control.zoom({position: 'topleft'}).addTo(map);
										var marker = L.marker([geodata[0]['lat'], geodata[0]['long']]).addTo(map); // from image
									</script>
```

![obrazek](https://user-images.githubusercontent.com/7648991/56054802-0c841a00-5d58-11e9-8016-385a425bc69e.png)


![02](https://user-images.githubusercontent.com/7648991/56054886-51a84c00-5d58-11e9-9866-4d566a8b7a1f.jpg)

**Comment by sbillard** [comment]
Can you try setting your site to en_US. I am guessing that the european number representation (comma for decimal separator) is the issue. Everything works when I am in English, but I get failures when I switch to Czech. But I am surprised that no one has reported this issue before.

**Comment by sbillard** [comment]
Ok, fixing the coordinates to use a period as the decimal separator works for me. I'll make a build and upload it so you can verify.

**Comment by Mates-K1** [comment]
It works. Many thanks 🥇
