### ISSUE TITLE
zpSkeleton Image Strip thumb size

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#957]
1.9.3.03

There is different size of thumbs for latest and random images. And they are align to column, not to row. :/

(in my case - latest images are all video thumbs...now)

![obrazek](https://user-images.githubusercontent.com/7648991/55953339-1fb1bf80-5c5c-11e9-9d8a-02cda6066450.png)

versus

![obrazek](https://user-images.githubusercontent.com/7648991/55953424-5c7db680-5c5c-11e9-97fd-08f830ba7ee4.png)

**Comment by Mates-K1** [comment]
And on the Contact page, there is only one thumb for random images, but nine thumbs for latest.

**Comment by sbillard** [comment]
The theme author made a conscious choice to put only one image on the contact page. Personally I think it is the right choice.

**Comment by Mates-K1** [comment]
> The theme author made a conscious choice to put only one image on the contact page. Personally I think it is the right choice.

It is...  strange but I will respect it. 👍

**Comment by Mates-K1** [comment]
It works, many thanks. 👍
