### ISSUE TITLE
Zenpage theme - more space for titles please

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#958]
![obrazek](https://user-images.githubusercontent.com/7648991/55955876-da44c080-5c62-11e9-95ae-89efa3e6f138.png)

**Comment by sbillard** [comment]
This is a bit problematical. THe space can be increased, but it is not possible to make it satisfy all possible titles. What I have done is increase it so two lines will show and set it to "hide" anything beyond that.

**Comment by Mates-K1** [comment]
It does not work for me. :(
Still the same in 1.09.03.03.10

![obrazek](https://user-images.githubusercontent.com/7648991/56014094-16743180-5cf4-11e9-8278-3c8f632b897d.png)

**Comment by sbillard** [comment]
Remember that browsers often cache CSS files. If the height of the bar has not changed then the CSS is not being refreshed.
