### ISSUE TITLE
Grey Higlights theme exception

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#959]
![obrazek](https://user-images.githubusercontent.com/7648991/55957017-9606ef80-5c65-11e9-973c-a5a8511ad3ac.png)

**Comment by sbillard** [comment]
Gray Highlights is no longer part of the distribution. You can fix your local copy by changing printZenphotoLink() to print_SW_Link()

**Comment by Mates-K1** [comment]
Sorry, i just didnt delete this theme from my gallery. I didnt use it...
