### ISSUE TITLE
OpenStreetMap plugin - clearer marker setting

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#963]
Now there are four checkboxes for marker setting. 
![obrazek](https://user-images.githubusercontent.com/7648991/56100102-6251f100-5f15-11e9-84b1-092ee0275967.png)
I think it is not almost clear as they work.

If I want marker with thumb and I check only "Marker popups with thumbs" it will not work. I need "Marker popups" checked to others work.

Is possible to make others grey (unactive, unable to check) if "Marker popups" is not checked?

**Comment by sbillard** [comment]
Hmm. I am not sure why there is even such a checkbox for "Marker popups" so I guess i am as confused as you. The only thing it seems to do is make the plugin ignore the checked settings of the other three options. 

How about we just remove "Marker popups" as a checkbox. Then if one of the marker selections is checked, you get it. If you want none then don't check any.

**Comment by Mates-K1** [comment]
What about this way?
![Nepojmenovaný 1](https://user-images.githubusercontent.com/7648991/56113955-b386d280-5f5f-11e9-9ac4-d62195965d45.jpg)

**Comment by Mates-K1** [comment]
Or "Marker popups with" ("with" on the left side).

**Comment by sbillard** [comment]
My thoughts exactly. Except the choices will be in-line. New version will be up shortly. I also discovered that the plugin was not attempting to compute the map center. That is now added as well.

**Comment by Mates-K1** [comment]
It seems much more clearer in v15. Thanks. 👍
