### ISSUE TITLE
OpenStreetMap plugin - album marks

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#964]
When I add _printOpenStreetMap();_ to album.php (zpArdroise) I get map, centered to images position, but without any markers.
![obrazek](https://user-images.githubusercontent.com/7648991/56122321-7546de80-5f72-11e9-863a-646b9e102175.png)

but in image.php (screenshot is after clicking cluster):
![obrazek](https://user-images.githubusercontent.com/7648991/56122374-927bad00-5f72-11e9-9163-e97f7b9e1ffc.png)

**Comment by sbillard** [comment]
Can you try this with the 1.9.03.3.15 build? You should not need to modify the theme any more. For me, the points show up.

**Comment by Mates-K1** [comment]
1.09.03.03.15 - sorry, it does not work for me. :( again, english work, czech not...

**effervescence+ theme:**

 `EXCEPTION (0): "syntax error, unexpected ';', expecting ')'" in /data/web/virtuals/172972/virtual/www/themes/effervescence+/image_gallery/functions.php on line 155 `

**garland theme:**

`POZNÁMKA: "Undefined variable: pints" in /data/web/virtuals/172972/virtual/www/themes/garland/album.php on line 129 `
and there is border around the marker
![obrazek](https://user-images.githubusercontent.com/7648991/56151431-8400b600-5fb1-11e9-8f21-d96abdb332e9.png)

**paradigm theme:**

` UPOZORNĚNÍ: "Use of undefined constant gmap_display - assumed 'gmap_display' (this will throw an Error in a future version of PHP)" in /data/web/virtuals/172972/virtual/www/themes/paradigm/image.php on line 146 `

`UPOZORNĚNÍ: "Use of undefined constant gmap_display - assumed 'gmap_display' (this will throw an Error in a future version of PHP)" in /data/web/virtuals/172972/virtual/www/themes/paradigm/album.php on line 59  `

**zpbootstrap theme:**
`POZNÁMKA: "Undefined variable: id" in /data/web/virtuals/172972/virtual/www/themes/zpBootstrap/inc_print_googlemap.php on line 37 `

**zpMobile theme:**
- image page - map dont load completely, map is not centered - image position is in upper left corner

**Comment by sbillard** [comment]
Try version ....16 for all but the last item.

**Comment by sbillard** [comment]
As for the zpMobile theme, I am at a loss. When I try to inspect the item to see what is controlling the size, it suddenly goes full frame. I suspect that there is a javascript conflict with the mobile theme javascript support. If that is the case, there is nothing I can do.

**Comment by Mates-K1** [comment]
It works. :) Thanks.
