### ISSUE TITLE
Update from 1.09.03.03.16 to 1.09.04.01

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#973]
![obrazek](https://user-images.githubusercontent.com/7648991/56638803-5da4df80-666f-11e9-8f00-315d7afa0505.png)

**Comment by sbillard** [comment]
What does the Czech part of the first error message say? Basically, the download of the update did not happen (reason in Czech.)

**Comment by Mates-K1** [comment]
Connection was inactive long time...
M.


On 24. 4. 2019 at 23:22, <Stephen <notifications@github.com>> wrote:

What does the Czech part of the first error message say? Basically, the
download of the update did not happen (reason in Czech.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZenPhoto20/netPhotoGraphics/issues/973#issuecomment-486431938>,
or mute the thread

**Comment by sbillard** [comment]
That says something went wrong on the GitHub end, I think. Anyway, the copy failed (which is what netPhotoGraphics showed in its error message.) The copy and install are working for me now. Have you tried again?

**Comment by Mates-K1** [comment]
Yes. But manually after about 5 minutes I had error. I was successfully.
At that time auto update still didn't work.


On 25. 4. 2019 at 1:15, <Stephen <notifications@github.com>> wrote:

That says something went wrong on the GitHub end, I think. Anyway, the copy
failed (which is what netPhotoGraphics showed in its error message.) The
copy and install are working for me now. Have you tried again?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZenPhoto20/netPhotoGraphics/issues/973#issuecomment-486461386>,
or mute the thread

**Comment by sbillard** [comment]
I do not know what would be causing this time-out. But there is nothing that can be done from netPhotoGraphics. Either the copy of the URL works or it does not. It could be some setting on your server, but there is nothing to help us know what that setting might be. Lots of servers have disabled copying from a URL, but most do that by disabling the "allow_url_fopen" PHP setting. If that were disabled, netPhotoGraphics would have reported it.

By manually, do you mean you downloaded the release and FTPed it to the site? Did the download button work or did you go to the repository and get the release.

**Comment by Mates-K1** [comment]
Yes, uploaded by FTP. Download button works fine.

Now, update from 1.09.04.01 to 1.09.04.02 was OK.

**Comment by sbillard** [comment]
OK. Nothing that can be done if the file copy does not work. But of course, there is always the fallback to the old FTP process. I will close this now.

**Comment by sbillard** [comment]
I am working on a different download mechanism that may fix this issue. It is in the development release, but of course until there is a release post your installing the fix it can't be tested.

**Comment by sbillard** [comment]
I believe that the CURL implementation will not have this issue. If it does not, there is nothing to be done on our end.
