### ISSUE TITLE
Site translations via Google

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/netPhotoGraphics#979]
Hi Stephen,

Something like this would make a great plugin and save a lot of work. Have you seen this operate?  Do you know if the Google translations are accurate? 
The example I found is for Wordpress. 
https://nl.wordpress.org/plugins/google-website-translator/

**Comment by sbillard** [comment]
I am sure you understand that there is no cross compatibility between 
plugins for wordpress and for netPhotoGrqphics. Besides which, we 
already recommend the tool PoEdit. Versions of PoEdit do provide for web 
based mechanical translations of the strings. But also, these 
translations are perhaps better than nothing, but are far from what a 
native speaker would do.

You can look at the result by reviewing the Dutch translations for 
netPhotoGraphics. I have used the web based translations to pre-load the 
strings. Those marked "fuzzy" or "needs work" are mechanical 
translations.

As you may remember I have tried to encourage you to look at these Dutch 
translations and improve upon them as only a native speaker can.


-Stephen

**Comment by Elinth** [comment]
I understand there is no cross compatibility with Wordpress. I merely thought the concept of this plugin is great and wanted your opinion on it. Yes I have looked at the po edit file, it gave me loads of errors in a busy time. I will have a look at it, I have not forgotten about it.

**Comment by sbillard** [comment]
Please try the 1.09.04.03.05 development release. Enable the new plugin googleTranslate. That plugin will put checkboxes in the "utilities" area of the object edit pages. There will be a check box for each field that can be translated, e.g. for article Content. Please review the plugin documentation for details.

Note, this does not help with "hard coded" language strings such as those that are passed to gettext(). Those must still be translated using the PoEdit facility.

**Comment by Elinth** [comment]
Stephen, this is truly brilliant! Amazing how accurate this works.

**Comment by Elinth** [comment]
Super glad what this does. Maybe just one more thought on this.. Would there be a way that you can mass translate underlying images in an album?

**Comment by Elinth** [comment]
Or is this hard with your robot note (plugin info) on google?

**Comment by sbillard** [comment]
I think it would pretty much invoke the robot block. Just my testing on a few languages and news articles and titles got me into that bind on my local test site.  (Granted I did this quite a few times.) You can try, though. on the images page you will find the check box for each image on the page! You would have to check each box, though. No mechanism to automatically check them all.

**Comment by Elinth** [comment]
Ah, I thought so, anyways it works brilliantly. Just some testing thingies I found. 
-Somehow in the text editing field of the image (edit -image field) I cannot scroll down. The scroll bar is missing.
 - When I click the button source code the field overlaps with the left admin menu. It would be better if the field has less width. Now it is hard to see the content because the menu is in the way. 
You can check these on my site.

**Comment by sbillard** [comment]
I can reproduce this. Strange. It works properly on the news pages. Have to figure out what is different.

**Comment by Elinth** [comment]
This works perfect, thank you!
