### ISSUE TITLE
disable download from html 5 video player

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/netPhotoGraphics#980]
When you play a video, you can right click the screen and there is the option to save the video. Is there a way this can be disabled as an option?

**Comment by sbillard** [comment]
Please see https://stackoverflow.com/questions/737022/how-do-i-disable-right-click-on-my-web-page

The summary of this is that you can disable the right click (context menu) but that does nothing to prevent a viewer from capturing your video. For instance, see https://clipgrab.org/

**Comment by Elinth** [comment]
ok, thanks for the link. I will let it go..
