### ISSUE TITLE
Next release features

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/netPhotoGraphics#985]
Hi @sbillard what will be the features of the next version of NPG ?

What will be the release date ?

Thank You

**Comment by sbillard** [comment]
Mostly the next release will be the re-branding--removing references to 
the old zenphoto (zp, etc.) part of that is "redirected" back-end links 
for better SEO. I do not have a release date in mind yet, but I think 
the re-branding changes are close to being done. I am still considering 
if it is practical to rename the zp-core folder. So far I have just 
"hidden" it with the back-end rewrite links.

With this kind of change there is a high chance of introducing mistakes, 
so testing is a must. You can preview these changes by installing the 
development build. In fact I would appreciate some other "eyes" in the 
testing process. You can use the repository for now. I will probably 
create an extract file in the next week or two so I can test on my 
hosted test sites. So far my testing has been on my local PC.


-Stephen

**Comment by By-oussef** [comment]
I think zp-core could be replaced by npg-core

**Comment by sbillard** [comment]
The repercussions of this change are not worth the benefit at this time. Perhaps the change can be migtated to over time. In the mean time the name is hidden by the "rewrite" on the back end urls. 

The dev release is ready if you can test it independently. It should not be put in production yet.
