### ISSUE TITLE
Question about News excerpts

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/netPhotoGraphics#986]
Hi Stephen,

Is it possible to display news excerpts based on category? I'd like to have the news filtered already based on the category. For instance, I have several family albums. For each family album I'd like to show the news for that family, which has its own category. I was thinking of putting the code in a code block for that album. Also I'd like to only show this news if there are no images found and when gallerific is not active. So for the albums that show no images.

**Comment by sbillard** [comment]
News is organized by the category. You could place a link on your album page to the news category for that family: .../category/family-name/ The process of listing news articles is pretty complex--that is why there is a  news.php script handling it in the theme. I do not recommend your trying to replicate that code in a codeblock.

You could override the album link with the category link {_printNewsCategoryURL()_} in your gallery script if there are no images in the album. But then how do you deal with the normal image that is shown?

**Comment by Elinth** [comment]
Thanks Stephen, Currently on my album page I use a right column which is empty at the moment. This is where I wanted to put the news excerpts. On the gallerific gallery album page I use the caption of gallerific in that column. This is where I wanted no news excepts as the caption is there. I was really looking for displaying excerpts based on category. I guess I will leave this alone.

**Comment by sbillard** [comment]
It would certainly be possible, but not simple. You would need to model 
the right column after the news page and force the category to be 
correct.


-Stephen

**Comment by Elinth** [comment]
Thanks Stephen,

The difficulty lies in the forcing of the category I guess. 
I'll leave it alone.
