### ISSUE TITLE
Crop thumbnail not working

### ISSUE THREAD

**Issue by Elinth** [ZenPhoto20/netPhotoGraphics#987]
Hi Stephen,

When I crop a thumbnail in the image admin page, I am able to crop, but once I press apply it says the page zp-core/admin-tabs/edit.php is not found. You can try it on my site.

**Comment by sbillard** [comment]
You can copy the file zp-core/admin-tabs/thumbcrop.php from the repository to your site and this should be fixed.

**Comment by Elinth** [comment]
Thanks!
