### ISSUE TITLE
Code quality | Scrutinizer

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/netPhotoGraphics#992]
This technology is the best toolbox for building better software. From continuous integration, and continuous analysis to empowering human code reviews with code intelligence.

This tool (scrutinizer-ci) scores your code based on cyclomatic complexity, coding standards, bugs, bad practices, etc. In other words, it presents a numeric representation of your overall code quality.

Check this list: https://scrutinizer-ci.com/explore/ (for example, you can check yii2 or cake).

https://scrutinizer-ci.com/

**Comment by sbillard** [comment]
What is your point? If you wish to use this tool, do so. netPhotoGraphics will continue to use gitHub

**Comment by By-oussef** [comment]
Hi Stephen I just installed the script for netphotographics and you can view the quality of the netphotographics code.
https://scrutinizer-ci.com/g/By-oussef/netPhotoGraphics-DEV/code-structure/master/hot-spots

**Comment by sbillard** [comment]
Well, this tool is really useless. It is analyzing each script as if it were stand-alone. So it complains about things that are simply not the case.
