### ISSUE TITLE
zenFluid theme main page error

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#995]
`CHYBA UŽIVATELE: "MySQLi Error: ( SELECT `id`, `folder`, `filename` FROM `_hlavniimages`, `_hlavnialbums` WHERE `_hlavnialbums`.folder!="" AND `_hlavniimages`.albumid = `_hlavnialbums`.id ORDER BY `_hlavniimages`.date DESC ) failed. MySQLi returned the error 1052: Column 'id' in field list is ambiguous" in /data/web/virtuals/172972/virtual/www/zp-core/functions-basic.php on line 19 `

**Comment by sbillard** [comment]
This is probably a day-one issue. Nothing changed here for the 2.0 release. I guess no one really uses zenFluid with "use random image" unchecked.
